In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread("cat2.jpg")
print(img)

[[[178 210 215]
  [180 212 217]
  [187 216 221]
  ...
  [211 220 240]
  [211 221 238]
  [206 222 229]]

 [[178 210 215]
  [180 212 217]
  [187 216 221]
  ...
  [216 226 244]
  [216 226 243]
  [210 224 236]]

 [[177 209 214]
  [180 212 217]
  [187 216 221]
  ...
  [215 225 242]
  [216 226 243]
  [208 219 239]]

 ...

 [[120 159 191]
  [118 157 189]
  [117 155 187]
  ...
  [191 207 220]
  [194 210 223]
  [192 208 221]]

 [[124 162 194]
  [122 160 192]
  [119 157 189]
  ...
  [194 210 223]
  [197 213 226]
  [193 209 222]]

 [[118 154 184]
  [119 155 185]
  [120 156 186]
  ...
  [194 210 223]
  [196 212 225]
  [196 212 225]]]


In [3]:
type(img)

numpy.ndarray

In [3]:
img = cv2.imread("cat2.jpg", cv2.IMREAD_GRAYSCALE)

In [4]:
img.dtype

dtype('uint8')

In [5]:
cat = cv2.imread("cat2.jpg")
cat.shape

(225, 225, 3)

In [7]:
gray = cv2.cvtColor(cat, cv2.COLOR_BGR2GRAY)

In [8]:
cv2.imshow('frame', gray)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [9]:
hsv = cv2.cvtColor(cat, cv2.COLOR_BGR2HSV)

In [10]:
cv2.imshow('frame', hsv)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [12]:
img1 = cv2.imread("cat2.jpg")
img2 = cv2.imread("cat2.jpg")

In [21]:
temp = img1
type(temp)

numpy.ndarray

In [22]:
temp.dtype

dtype('uint8')

In [ ]:
temp[0:100, 100:300] = 0

In [26]:
cv2.imshow('temp',temp)
cv2.imshow('img1',img1)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [16]:
temp2 = img2.copy()
temp2[0:100, 100:300] = 0

In [17]:
cv2.imshow('temp2',temp2)
cv2.imshow('image1',img2)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [18]:
from copy import deepcopy

In [20]:
cat[:, :, 2].max()

np.uint8(255)

In [21]:
cat.shape

(225, 225, 3)

In [27]:
img1[0:100, 150:200] = img1[100:200, 0:50]
cv2.imshow('img1',img1)
cv2.waitKey(1000)
cv2.destroyAllWindows()

## (BGR uses indices: 0=Blue, 1=Green, 2=Red)

In [26]:
arr_ = np.array([1, 2, 3]) * 3

In [29]:
b, g, r = cv2.split(img1)

In [30]:
b

array([[178, 180, 187, ...,   0,   0,   0],
       [178, 180, 187, ...,   0,   0,   0],
       [177, 180, 187, ...,   0,   0,   0],
       ...,
       [120, 118, 117, ..., 191, 194, 192],
       [124, 122, 119, ..., 194, 197, 193],
       [118, 119, 120, ..., 194, 196, 196]], shape=(225, 225), dtype=uint8)

In [35]:
rgb = cv2.merge((r ,b ,g))
brg = cv2.merge((b ,r ,g))
bgr = cv2.merge((b ,g, r))

In [36]:
cv2.imshow('image1',bgr)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [41]:
cv2.imshow('img', cat[:, :, 0])
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [44]:
im = cv2.imread('cat2.jpg')
im[:, :, 0] = 0
im[:, :, 1] = 0
cv2.imshow('img1', im)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [50]:
im.dtype

dtype('uint8')

### For np.zeros we have to include dtype. For np.zeros_like it's not mandatory

In [48]:
new_image = np.zeros(im.shape, dtype ='uint8')

In [46]:
new_image[:, :, 0]= im[:, :, 0]

In [47]:
cv2.imshow('image1',new_image)
cv2.waitKey(1000)
cv2.destroyAllWindows()

* cv2.BORDER_CONSTANT (Adds a border filled with a solid color)
* cv2.BORDER_REFLECT (Adds a border by reflecting/mirroring the image edges)

In [55]:
padded_img = cv2.copyMakeBorder(im, 20, 20, 10, 0, cv2.BORDER_CONSTANT, value = (255,255,255))

In [56]:
cv2.imshow('image1',padded_img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [53]:
padded_img1 = cv2.copyMakeBorder(im, 40, 40, 40, 40, cv2.BORDER_REFLECT)

In [54]:
cv2.imshow('image1',padded_img1)
cv2.waitKey(1000)
cv2.destroyAllWindows()