In [5]:
# SESSION 1
print("Hello World")

a = 10
b = 4

print(a+b)
# print(c)

Hello World
14


# Session 1
### computer vision

- a
- b 
- c

this is a test

In [6]:
import numpy as np
import cv2

In [8]:
image = cv2.imread("Lucy.jpg")

In [9]:
print(image)

[[[217 218 216]
  [217 218 216]
  [217 218 216]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 [[217 218 216]
  [217 218 216]
  [217 218 216]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 [[216 217 215]
  [216 217 215]
  [216 217 215]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 ...

 [[206 210 211]
  [204 208 209]
  [200 204 205]
  ...
  [167 173 180]
  [167 173 180]
  [167 173 180]]

 [[203 207 208]
  [201 205 206]
  [198 202 203]
  ...
  [167 173 180]
  [167 173 180]
  [166 172 179]]

 [[202 206 207]
  [200 204 205]
  [196 200 201]
  ...
  [167 173 180]
  [167 173 180]
  [167 173 180]]]


In [10]:
type(image)

numpy.ndarray

In [11]:
image.dtype

dtype('uint8')

In [12]:
image.shape

(598, 960, 3)

In [13]:
image.max()

np.uint8(255)

In [16]:
print(image.min())

0


In [17]:
image.min()

np.uint8(0)

In [ ]:
[1,2 , 5, 9]
[1, 2, 3, 4]

def func(a, b):
    pass

def func2(a, func):
    pass

In [ ]:
cv2.imshow('name', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
image[:, :, 0].shape

(598, 960)

In [24]:
image[:, :, 1].shape

(598, 960)